16:37:29.371 [pool-2-thread-3] ERROR errorLogger - [Ljava.lang.StackTraceElement;@41130e96
dao.exception.DaoException: Can't delete task. Update failed
	at dao.jdbc.JdbcTaskDao.deleteTask(JdbcTaskDao.java:227) ~[classes/:?]
	at dao.jdbc.JdbcTaskDao.processTask(JdbcTaskDao.java:152) ~[classes/:?]
	at dao.jdbc.JdbcTaskDao.processTaskList(JdbcTaskDao.java:134) ~[classes/:?]
	at dao.jdbc.JdbcTaskDao.updateTaskList(JdbcTaskDao.java:117) ~[classes/:?]
	at dao.jdbc.JdbcUserDao.updateUser(JdbcUserDao.java:106) ~[classes/:?]
	at controller.UserController.update(UserController.java:34) ~[classes/:?]
	at network.RequestHandler.run(RequestHandler.java:71) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
